# -*- coding: utf-8 -*-
"""GPT4 generated emails match the human annotations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZF3bhkmvyDFYYnhJV3EXr5Zb8MdufVF
"""

import pandas as pd
import numpy as np
from scipy.stats import spearmanr
import matplotlib.pyplot as plt

# -----------------------
# INPUT (your uploaded CSV)
# -----------------------
PATH = "/data/validation/second_csv_with_gold_and_seed_no_variant_id.csv"

LEVEL_COL = "level"  # GPT intended politeness level (1..5)

DIMS = {
    "Directness vs Indirectness": "Directness_vs_Indirectness__GOLD",
    "Positive Face Saving": "Structural_Politeness_and_Politeness_Markers__GOLD",
    "Negative Face Saving": "Tone_and_Overall_Consideration__GOLD",
}

df = pd.read_csv(PATH)

# keep only required columns, drop missing
keep_cols = [LEVEL_COL] + list(DIMS.values())
df = df[keep_cols].dropna()

# ensure level is int in [1,5]
df[LEVEL_COL] = df[LEVEL_COL].astype(int)
df = df[df[LEVEL_COL].between(1, 5)].copy()

# -----------------------
# Bootstrap CI for Spearman rho
# -----------------------
def bootstrap_spearman_ci(x, y, n_boot=4000, seed=13):
    rng = np.random.default_rng(seed)
    x = np.asarray(x)
    y = np.asarray(y)
    n = len(x)
    rhos = np.empty(n_boot, dtype=float)
    for i in range(n_boot):
        idx = rng.integers(0, n, size=n)
        rhos[i], _ = spearmanr(x[idx], y[idx])
    lo, hi = np.percentile(rhos, [2.5, 97.5])
    return float(lo), float(hi)

# -----------------------
# Build Table X
# -----------------------
levels = [1, 2, 3, 4, 5]
means_by_level = df.groupby(LEVEL_COL).mean(numeric_only=True)

rows = []
for dim_name, col in DIMS.items():
    rho, p = spearmanr(df[LEVEL_COL], df[col])
    ci_lo, ci_hi = bootstrap_spearman_ci(df[LEVEL_COL], df[col])

    means = [means_by_level.loc[l, col] if l in means_by_level.index else np.nan for l in levels]
    delta = means[-1] - means[0]  # L5 - L1

    rows.append({
        "Dimension": dim_name,
        "Spearman_rho": rho,
        "rho_CI95": f"[{ci_lo:.3f}, {ci_hi:.3f}]",
        "p_value": p,
        "Mean_L1": means[0],
        "Mean_L2": means[1],
        "Mean_L3": means[2],
        "Mean_L4": means[3],
        "Mean_L5": means[4],
        "Delta_L5-L1": delta
    })

tableX = pd.DataFrame(rows)

# pretty print
table_show = tableX.copy()
for c in ["Spearman_rho","Mean_L1","Mean_L2","Mean_L3","Mean_L4","Mean_L5","Delta_L5-L1"]:
    table_show[c] = table_show[c].map(lambda v: f"{v:.3f}")
table_show["p_value"] = table_show["p_value"].map(lambda v: f"{v:.2e}")

print("\n=== Table X: Alignment between GPT intended level (1–5) and human gold scores ===")
print(table_show[["Dimension","Spearman_rho","rho_CI95","p_value",
                  "Mean_L1","Mean_L2","Mean_L3","Mean_L4","Mean_L5","Delta_L5-L1"]])

# -----------------------
# Plot: mean ± 95% CI of mean vs level
# -----------------------
plt.figure()

for dim_name, col in DIMS.items():
    g = df.groupby(LEVEL_COL)[col]
    means = g.mean().reindex(levels)
    sem = g.sem().reindex(levels)
    ci = 1.96 * sem  # normal approx CI for mean

    plt.plot(levels, means.values, marker="o", label=dim_name)
    plt.fill_between(levels, (means - ci).values, (means + ci).values, alpha=0.2)

plt.xticks(levels)
plt.xlabel("GPT-4o intended politeness level (1=least, 5=most)")
plt.ylabel("Human gold document-level score")
plt.title("Alignment of GPT-4o politeness levels with human annotations")
plt.legend()
plt.tight_layout()
plt.savefig("gpt_level_alignment.pdf", dpi=200)
print("\nSaved plot: gpt_level_alignment.pdf")

# -----------------------
# Export ACL-friendly LaTeX table
# -----------------------
latex = table_show[["Dimension","Spearman_rho","rho_CI95",
                    "Mean_L1","Mean_L2","Mean_L3","Mean_L4","Mean_L5","Delta_L5-L1"]].to_latex(
    index=False,
    escape=False,
    column_format="lcccccccc",
    caption=("Alignment between GPT-4o intended politeness levels (1--5) and human gold document-level scores. "
             "We report Spearman $\\rho$ (with 95\\% bootstrap CI) and mean gold scores per level."),
    label="tab:gpt_level_alignment"
)

with open("tableX_gpt_level_alignment.tex", "w", encoding="utf-8") as f:
    f.write(latex)

print("Saved LaTeX table: tableX_gpt_level_alignment.tex")