# -*- coding: utf-8 -*-
"""generating_more_polite_version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IojqnYFqRNxxb7Sz2lZBno4Q3BtYFVN5
"""

import openai
import pandas as pd
import os

# The OpenAI API key should be provided through the
# OPENAI_API_KEY environment variable.
client = openai.OpenAI()

# Initialize the OpenAI client
client = openai.OpenAI()

def make_polite_version(Rude_emails, model="gpt-4o", tone="professional", style="polite"):
    """
    Generate four polite versions of the given email using OpenAI's GPT-4o model.
    Each version is generated based on the same original rude email.
    Each subsequent polite version in this sequential order is expected to be more polite than its preceding counterpart.
    :param rude_email: The original rude email to be transformed.
    :param model: The model to use for generating the polite versions.
    :return: A list containing four increasingly polite versions of the same original rude email.
    """

    prompt = f"""
    Transform the following full email conversation—including both the original email and any reply into a list containing four increasingly polite versions of the same original rude email:"
    '{Rude_emails}'

        Ensure that the transformation:
        - Retains the original intent and meaning.
        - Be realistic, coherent, and well-structured.
        - Each subsequent polite version in this sequential order is expected to be more polite than its preceding counterpar with a total of four polite versions such that the first polite version (E1) is less polite than the second (E2), the second is less polite than the third (E3), and the third is less polite than the fourth (E4).
        - Enhances the positive and negative face of both the sender and the receiver, increasingly according to politeness level.
          Positive face refers to the need to be liked, appreciated, and valued, suggesting the use of compliments and expressions of gratitude.
          Negative face refers to the need for autonomy and respect for one’s choices, suggesting the use of indirect language and offering options.
        - Enhance Positive Politeness, increasingly according to politeness level.
          Positive Politeness refers to the strategies aimed at emphasizing friendliness and common ground, often through compliments, expressions of solidarity, and affirming the interlocutor's positive face needs.
        - Enhance Negative Politeness increasingly according to politeness level.
          Negative Politeness refers to the strategies aimed at acknowledging the imposition of the act and showing deference, often through indirectness, hedging, and expressions of respect for the interlocutor's negative face needs.
        - Enhance Off-Record strategies that hint at or imply something without directly stating it, thus reducing the imposition on the interlocutor.
        - Minimize face-threatening acts by employing strategies like hedging, apologizing, and using polite modals (e.g., could, would), decreasingly according to politeness level.
        - Ensure the email is transformed to minimize face-threatening acts by using strategies that mitigate potential threats, such as politeness strategies like indirectness, hedging, and expressing gratitude or appreciation, to strengthen interpersonal relations and maintain the original intent and meaning of the email.
        - Apply the rational agents theory, considering the impact of communicative acts on one's own and others' face, emphasizing how behavior affects relationships and perceptions.
        - Ensure each subsequent version is more polite than the last one, such that versions of polite emails derived from the same original {Rude_emails}.
        - Do not use any stars, asterisks, or additional markdown formatting in the subject lines or email version labels. They should be plain text only.
        - Do not include any extra introductory text or comments before generating the email versions.
        - The output should start directly with "1. Email Version 1 (E1):" and continue sequentially.
        - Maintain the {tone} and the {style}.
        - Do NOT enhance Salutation (opening part) and Complimentary close (closing part), increasingly according to politeness level.
        """
    try:
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "system", "content": "You are an advanced email paraphraser for politeness task that paraphrases each subsequent polite version in a sequential order is expected to be more polite than its preceding counterpart."},
                      {"role": "user", "content": prompt}
                           ]
        )

            new_version = response.choices[0].message.content
            if not new_version:
                raise ValueError("Failed to generate a polite version.")
            return new_version
    except Exception as e:
        print(f"An error occurred while generating the polite version: {e}")
        return f"Error generating polite version"

# Example usage:
csv_file_path = '/data/raw/face_threatening_emails_July2025_ShowToAnnotators_stripped_2.csv' # july
df = pd.read_csv(csv_file_path)

# Process each email to generate a polite version
df['polite_version'] = df['Rude_emails'].apply(make_polite_version)

output_file_path = '/data/raw/face_threatening_balanced_selected_replies_4_More_polite_July2025.csv'

df.to_csv(output_file_path, index=False)
print("Polite versions for each email have been generated and saved to CSV.")