# -*- coding: utf-8 -*-
"""generating_face_threatening_emails.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_YOr59EUQVyj4C71sskhTVLhRhGumSv
"""

#four distinct replies:
 #     - Reply 1: Accept the sender’s FTA using face-saving (polite) language.
 #     - Reply 2: Reject the sender’s FTA using face-threatening (impolite) language aimed at the sender.
 #     - Reply 3: Accept the sender’s FTA using face-threatening (impolite) language.
 #     - Reply 4: Reject the sender’s FTA using face-saving (polite) language.

import openai
import csv
import os
import pandas as pd
import random

# The OpenAI API key should be provided through the
# OPENAI_API_KEY environment variable.
client = openai.OpenAI()

# Function to generate emails based on a context
def generate_email(context, model="gpt-4o", tone="professional", max_words=150):
    """
    Generates an email based on the provided context with four distinct replies:
      - Reply 1: Accept the sender’s FTA using face-saving (polite) language.
      - Reply 2: Reject the sender’s FTA using face-threatening (impolite) language aimed at the sender.
      - Reply 3: Accept the sender’s FTA using face-threatening (impolite) language.
      - Reply 4: Reject the sender’s FTA using face-saving (polite) language.
    """
    try:
        messages = [
            {
                "role": "system",
                "content": "You are an advanced emails and replies generator."
            },
            {
                "role": "user",
                "content": f"""
### Requirements for the email:
  - Be realistic and creative.
  - Generate an email based on context: '{context}'.
  - The context: '{context}' should be clearly incorporated into the email.
  - The email should intentionally challenge the recipient's self-image and autonomy.
  - Do not appreciate or value the recipient, and do not acknowledge their achievements.
  - Do not mitigate any Face Threatening Act (FTA) as described by Brown and Levinson's politeness theory.
  - Avoid compliments that might mitigate both their positive and negative faces.
  - The email should be in a {tone} tone.
  - Include diverse sender and recipient names and professional positions.
  - End with a closing and a sender signature.
  - Stay under {max_words} words.
  - Do not use any stars, asterisks, extra separator lines, or additional markdown formatting.
  - Do not include any extra introductory text or comments before generating the email.

### Reply Requirements:
  - The email output must include four replies appended directly after the main email text.
  - Reply 1 must accept the sender’s FTA, using face-saving (polite) language. Prefix it with "Reply: Accept-Polite:".
  - Reply 2 must reject the sender’s FTA, using face-threatening (impolite) language aimed at the sender. Prefix it with "Reply: Reject-Impolite:".
  - Reply 3 must accept the sender’s FTA, using face-threatening (impolite) language. Prefix it with "Reply: Accept-Impolite:".
  - Reply 4 must reject the sender’s FTA, using face-saving (polite) language. Prefix it with "Reply: Reject-Polite:".
  - All replies must be realistic, coherent, and well-structured.
  - The replies must match the {tone} of the original email.
  - Each reply should be no longer than {max_words} words.
  - Each reply must start on a new line with the specified prefix.
  - Contextual keywords: {context}
                """
            }
        ]


        response = client.chat.completions.create(
            model=model,
            messages=messages,
        )

        return response.choices[0].message.content
    except Exception as e:
        print(f"An error occurred: {e}")
        return ""

# Function to read the CSV file containing top words per topic
def get_top_words_per_topic(top_words_per_topic_path):
    """
    Reads the CSV file containing the top words per topic and returns a DataFrame with the topic and its top words.

    :param top_words_per_topic_path: Path to the CSV file containing top words per topic.
    :return: DataFrame with columns ['Topic', 'Top_n_words'].
    """
    try:
        top_words_per_topic = pd.read_csv(top_words_per_topic_path)
        return top_words_per_topic
    except Exception as e:
        print(f"An error occurred while reading the file: {e}")
        return pd.DataFrame(columns=['Topic', 'Top_n_words'])  # Return an empty DataFrame if there's an error

# Path to the CSV file containing top words per topic
top_words_per_topic_path = '/data/raw/cleaned_top_n_words_non_spam_emails_Enron_46.9M_FINAL.csv'

# Get top words per topic
top_words_per_topic = get_top_words_per_topic(top_words_per_topic_path)

# CSV file path for the impolite emails
csv_file_path = '/data/raw/face_threatening_emails_July2025_ToHaveMoreSNEGPos_ShowToAnnotators.csv'

# Write column names to the CSV file
with open(csv_file_path, 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Top_n_words', 'Rude_Email_with_Four_Replies'])

# Iterate over each topic and generate impolite emails
for index, row in top_words_per_topic.iterrows():
    #topic = row['Topic']
    top_words = row['Top_n_words']

    # Generate 2 different impolite emails for each topic
    for i in range(1):
        # Generate email for the current topic's top words
        email = generate_email(top_words)

        # Append to CSV file
        with open(csv_file_path, 'a', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow([top_words, email])

print("All impolite emails generated in {csv_file_path}")